# Generated by Django 2.2.17 on 2021-01-17 17:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sum_point', models.IntegerField(default=0)),
                ('user_me', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_me', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CardBattle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_user_num', models.IntegerField(blank=True, null=True)),
                ('to_user_card_num', models.IntegerField(blank=True, choices=[(8, 8), (7, 7), (6, 6), (5, 5), (9, 9)], null=True)),
                ('from_user_card_num', models.IntegerField(blank=True, choices=[(8, 8), (7, 7), (6, 6), (5, 5), (9, 9)], null=True)),
                ('result', models.CharField(blank=True, max_length=255, null=True)),
                ('to_user_result', models.CharField(blank=True, max_length=255, null=True)),
                ('from_user_result', models.CharField(blank=True, max_length=255, null=True)),
                ('to_user_point', models.IntegerField(default=0)),
                ('from_user_point', models.IntegerField(default=0)),
                ('up_or_down', models.IntegerField(blank=True, null=True)),
                ('game_option', models.CharField(blank=True, max_length=255, null=True)),
                ('from_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='from_user', to=settings.AUTH_USER_MODEL)),
                ('to_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='to_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
