# Generated by Django 2.2.17 on 2021-01-18 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cardbattle',
            name='from_user_card_num',
            field=models.IntegerField(blank=True, choices=[(6, 6), (3, 3), (5, 5), (1, 1), (9, 9)], null=True),
        ),
        migrations.AlterField(
            model_name='cardbattle',
            name='to_user_card_num',
            field=models.IntegerField(blank=True, choices=[(6, 6), (3, 3), (5, 5), (1, 1), (9, 9)], null=True),
        ),
    ]
