# Generated by Django 2.2.17 on 2021-01-16 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cardbattle',
            name='game_option',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='cardbattle',
            name='up_or_down',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cardbattle',
            name='from_user_card_num',
            field=models.IntegerField(blank=True, choices=[(2, 2), (10, 10), (9, 9), (8, 8), (5, 5)], null=True),
        ),
        migrations.AlterField(
            model_name='cardbattle',
            name='to_user_card_num',
            field=models.IntegerField(blank=True, choices=[(2, 2), (10, 10), (9, 9), (8, 8), (5, 5)], null=True),
        ),
    ]
