# Generated by Django 2.2.17 on 2021-01-18 02:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cardbattle',
            name='from_user_card_num',
            field=models.IntegerField(blank=True, choices=[(8, 8), (9, 9), (1, 1), (3, 3), (10, 10)], null=True),
        ),
        migrations.AlterField(
            model_name='cardbattle',
            name='to_user_card_num',
            field=models.IntegerField(blank=True, choices=[(8, 8), (9, 9), (1, 1), (3, 3), (10, 10)], null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='user_me',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_me', to=settings.AUTH_USER_MODEL, unique=True),
        ),
    ]
