# Generated by Django 2.2.17 on 2021-01-18 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_auto_20210118_1133'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cardbattle',
            name='from_user_card_num',
            field=models.IntegerField(blank=True, choices=[(4, 4), (3, 3), (9, 9), (10, 10), (1, 1)], null=True),
        ),
        migrations.AlterField(
            model_name='cardbattle',
            name='to_user_card_num',
            field=models.IntegerField(blank=True, choices=[(4, 4), (3, 3), (9, 9), (10, 10), (1, 1)], null=True),
        ),
    ]
