# Generated by Django 2.2.17 on 2021-01-19 22:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_auto_20210120_0739'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cardbattle',
            name='from_user_card_num',
            field=models.IntegerField(blank=True, choices=[(5, 5), (2, 2), (3, 3), (7, 7), (1, 1)], null=True, verbose_name='내가 고른 카드'),
        ),
        migrations.AlterField(
            model_name='cardbattle',
            name='to_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='to_user', to=settings.AUTH_USER_MODEL, verbose_name='도전장을 내밀 상대는?'),
        ),
        migrations.AlterField(
            model_name='cardbattle',
            name='to_user_card_num',
            field=models.IntegerField(blank=True, choices=[(5, 5), (2, 2), (3, 3), (7, 7), (1, 1)], null=True),
        ),
    ]
