# Generated by Django 2.2.17 on 2021-01-18 02:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_auto_20210118_1136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cardbattle',
            name='from_user_card_num',
            field=models.IntegerField(blank=True, choices=[(10, 10), (4, 4), (8, 8), (5, 5), (9, 9)], null=True),
        ),
        migrations.AlterField(
            model_name='cardbattle',
            name='to_user_card_num',
            field=models.IntegerField(blank=True, choices=[(10, 10), (4, 4), (8, 8), (5, 5), (9, 9)], null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='user_me',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_me', to=settings.AUTH_USER_MODEL),
        ),
    ]
