# Generated by Django 2.2.17 on 2021-01-18 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0004_auto_20210118_1144'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cardbattle',
            name='from_user_card_num',
            field=models.IntegerField(blank=True, choices=[(10, 10), (4, 4), (2, 2), (9, 9), (7, 7)], null=True),
        ),
        migrations.AlterField(
            model_name='cardbattle',
            name='to_user_card_num',
            field=models.IntegerField(blank=True, choices=[(10, 10), (4, 4), (2, 2), (9, 9), (7, 7)], null=True),
        ),
    ]
