# Generated by Django 2.2.17 on 2021-01-19 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0004_auto_20210120_0740'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cardbattle',
            name='from_user_card_num',
            field=models.IntegerField(blank=True, choices=[(9, 9), (1, 1), (3, 3), (2, 2), (4, 4)], null=True, verbose_name='내가 고른 카드'),
        ),
        migrations.AlterField(
            model_name='cardbattle',
            name='to_user_card_num',
            field=models.IntegerField(blank=True, choices=[(9, 9), (1, 1), (3, 3), (2, 2), (4, 4)], null=True),
        ),
    ]
