# Generated by Django 2.2.17 on 2021-01-19 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0005_auto_20210120_0750'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cardbattle',
            name='from_user_card_num',
            field=models.IntegerField(blank=True, choices=[(10, 10), (3, 3), (4, 4), (8, 8), (2, 2)], null=True, verbose_name='내가 고른 카드'),
        ),
        migrations.AlterField(
            model_name='cardbattle',
            name='to_user_card_num',
            field=models.IntegerField(blank=True, choices=[(10, 10), (3, 3), (4, 4), (8, 8), (2, 2)], null=True, verbose_name='내가 고른 카드'),
        ),
    ]
