# Generated by Django 2.2.17 on 2021-01-18 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0005_auto_20210118_1152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cardbattle',
            name='from_user_card_num',
            field=models.IntegerField(blank=True, choices=[(10, 10), (6, 6), (3, 3), (1, 1), (2, 2)], null=True),
        ),
        migrations.AlterField(
            model_name='cardbattle',
            name='to_user_card_num',
            field=models.IntegerField(blank=True, choices=[(10, 10), (6, 6), (3, 3), (1, 1), (2, 2)], null=True),
        ),
    ]
