# Generated by Django 2.2.17 on 2021-01-18 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0007_auto_20210118_1546'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cardbattle',
            name='from_user_card_num',
            field=models.IntegerField(blank=True, choices=[(1, 1), (2, 2), (6, 6), (5, 5), (3, 3)], null=True),
        ),
        migrations.AlterField(
            model_name='cardbattle',
            name='to_user_card_num',
            field=models.IntegerField(blank=True, choices=[(1, 1), (2, 2), (6, 6), (5, 5), (3, 3)], null=True),
        ),
    ]
