# Generated by Django 2.2.17 on 2021-01-22 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0007_auto_20210120_1821'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='rank',
        ),
        migrations.AlterField(
            model_name='cardbattle',
            name='from_user_card_num',
            field=models.IntegerField(blank=True, choices=[(8, 8), (3, 3), (6, 6), (7, 7), (5, 5)], null=True, verbose_name='내가 고른 카드'),
        ),
        migrations.AlterField(
            model_name='cardbattle',
            name='to_user_card_num',
            field=models.IntegerField(blank=True, choices=[(8, 8), (3, 3), (6, 6), (7, 7), (5, 5)], null=True, verbose_name='내가 고른 카드'),
        ),
    ]
